# Generated by Django 5.2.8 on 2025-11-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='license_number',
        ),
    ]
