# Generated by Django 5.2.8 on 2025-11-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_remove_customer_license_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='bike',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
